### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chdoig** [chdoig/acm-sigkdd-topic-modeling#1]
- [ ] Add more information on the convergence of the algorithm
- [ ] Add visualizations and applications section
- [ ] Comparison with LSA/LSI
- [ ] How do you close the loop after getting your results
- [ ] Code of the whole loop/pipeline
- [ ] Expand Dynamic topic Models section
